services:
  db:
    image: postgres:15
    container_name: weather_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=weather_db
    ports: "5432:5432"
    restart: unless-stopped
  web:
    build: .
    container_name: weather_app
    ports: "8000:8000"
    depends_on: db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/weather_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data: 